# Generated by Django 3.0 on 2021-05-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebox',
            name='img',
        ),
        migrations.AddField(
            model_name='medicineinfo',
            name='impf',
            field=models.ImageField(default='Ngo1.jpg', upload_to='Medicines/'),
        ),
        migrations.AddField(
            model_name='servicebox',
            name='impf',
            field=models.ImageField(default='Ngo1.jpg', upload_to='Medicines/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='impf',
            field=models.ImageField(default='Ngo1.jpg', upload_to='Medicines/'),
        ),
    ]
