# Generated by Django 3.0 on 2021-05-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_auto_20210511_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineinfo',
            name='impf',
            field=models.ImageField(default='ngo1.jpg', upload_to='Medicines/'),
        ),
        migrations.AlterField(
            model_name='servicebox',
            name='impf',
            field=models.ImageField(default='ngo1.jpg', upload_to='Medicines/'),
        ),
    ]
