# Generated by Django 3.0 on 2021-05-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_auto_20210511_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineinfo',
            name='organization_name',
            field=models.CharField(default='ngo', max_length=120),
        ),
    ]
