# Generated by Django 3.0 on 2021-05-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0004_medicineinfo_organization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='impf',
            field=models.ImageField(default='ngo1.jpg', upload_to='Medicines/'),
        ),
    ]
