# Generated by Django 3.0 on 2021-05-13 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_medicineinfo_days_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineinfo',
            name='current_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
